changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🛠 Breaking changes
      labels:
        - breaking-change
    - title: 🎉 Exciting new features
      labels:
        - enhancement
    - title: 👎 Deprecations
      labels:
        - deprecation
    - title: 🐛 Bug fixes
      labels:
        - bug
    - title: 📄 Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
